const translations = {
  en: {
    nav_home: "Home",
    nav_about: "About Us",
    nav_menu: "Our Menu",
    nav_pages: "Pages",
    nav_blog: "Blog",
    nav_contact: "Contact Us",
    call: "Call - 123 456 789",
    reservation_btn: "Reservation",
    hero_title_1: "Welcome to",
    author_desc_4: "A Restaurant with a lovely bar and intimate dining area. Food is sensational, exciting, highly innovative, the service is friendly & professional.", 
    hero_title_2: "Restaurant",
    hero_desc: "The people, food and the prime locations make the perfect place good friends & family to come together and have great time.",
    view_menu: "View Menu",
    locate_us: "Locate Us",
    locate_address: "Riverside 25, San Diego, California",
    open_hours: "Open Hours",
    open_time: "Mon To Fri 9:00 AM - 9:00 PM",
    reservation: "Reservation",
    story_title: "The Delicious Story",
    story_desc: "The people, food and the prime locations make the perfect place for the friends & family to come together and have great time.",
    story_2018: "Plan for this restaurant to deliver healthy food.",
    story_2022: "Happily in the fourth year by fulfill the motto.",
    menu_subtitle: "Menu",
    starters_title: "Try Our Special dishes",
    starters_text: "Every time you perfectly dine with us, it should happy for great inspired food in an environment designed with individual touches unique to the local area.",
    see_all_dishes: "See all dishes",
    starters: "Starters",
    main_dish: "Main Dish",
    desserts: "Desserts",
    author_desc_2: "I have visited this fantastic restaurant on several occasions food is absolutely outstanding & attention to detail is in league of its own",
    testimonial_subtitle: "Testimonial",
    author_desc_3: "Perfectly known for its fabulous taste and food. Anywhere your hunger is satisfied. They give best fried chicken and burgers those are yummy.",
    clients_say: "our clients say",
    clients_desc: "We love to hear from customers, so please leave a comment or say hello in an email.",
    offers_subtitle: "offers",
    offers_title: "Our Offer dishes",
    offers_desc: "Our chefs create melt-in-your-mouth dishes that'll satiate even the fussiest eaters now the dishes are in offers use it based on hunger.",
    offer_going: "50% Offer Going",
    chicken_burger: "Chicken Burger",
    chicken_burger_desc: "Chicken burger with the tasty toppings and leaves.",
    chicken_pizza: "Chicken Pizza",
    chicken_pizza_desc: "Pizza with multiple flavor and the toping are mixed.",
    only: "Only",
    popular_subtitle: "menu",
    popular_title: "Popular Dishes",
    popular_desc: "There is a game between the waiters in restaurant to see who serves the food to each table fastest. That led to attempting the Guinness Record.",
    chicken_manjoori: "Chicken Manjoori",
    chicken_manjoori_desc: "Dish relished by all age groups as a starter dish at parties.",
    hotdog: "Hotdog",
    hotdog_desc: "Grilled sausage served in the slit of a partially sliced bun.",
    fresh_salmon: "Fresh Salmon",
    fresh_salmon_desc: "Beat the health blues with our Super Immune Blue Juice Recipe.",
    veg_burger: "Veg Burger",
    veg_burger_desc: "Burgers may be made from ingredients like beans.",
    what_we_offer: "What we offer",
    our_services: "Our Great Services",
    services_desc: "The atmosphere set the stage. It's about more than just a dining room away from your home. food takes the spotlight as guests.",
    opened_247: "Opened 24/7",
    special_menus: "Special Menus",
    home_delivery: "Home Delivery",
    blog_subtitle: "Blog",
    blog_title: "Be First Who Read News",
    blog_desc: "Explore the latest stories about our dishes, offers, events and future plans here.",
    view_more: "View More",
    blog_cat_delicious: "Delicious",
    blog_cat_cooking: "Cooking",
    blog_story_1: "The Legend of US Cuisine: The Story of Hungry People",
    blog_story_1_desc: "Capitalize on low-hanging fruit to identify a ballpark value added matrix economically and the creative activity to beta test override the food quality.",
    blog_story_2: "The Most Popular Delicious Food of Mediterranean Cuisine",
    blog_story_2_desc: "Strategies on low-hanging fruit to identify a ballpark value added matrix economically and the creative activity to beta test override the food quality.",
    reserve_subtitle: "reservation",
    book_table: "Book Your Table",
    contact: "Contact",
    working_hours: "Working Hours",
    subscribe_content: "Join our mailing list for updates, Get news & offers events.",
    submit: "Submit",
    mon_fri: "Mon - Fri:",
    sat: "Sat:",
    sun: "Sun:",
    copyright: `© Copyright - TastEat | Designed by <a href="https://www.victorflow.com/" target="_blank">VictorFlow</a> - Powered by <a href="https://webflow.com/" target="_blank">Webflow</a>`,
    raw_scallops: "Raw Scallops from Erquy",
    raw_scallops_desc: "Shuck the scallop to that used for oysters",
    spring_roll: "Spring Roll",
    spring_roll_desc: "Add oil to a hot pan spring onion whites",
    french_onion: "French Onion Soup",
    french_onion_desc: "Wheat flour, apple cider vinegar, bread",
    tomato_bruschetta: "Tomato Bruschetta",
    tomato_bruschetta_desc: "Bread, olive oil, garlic, black pepper",
    grilled_salmon: "Grilled Salmon with Dill Sauce",
    grilled_salmon_desc: "Brown sugar, salmon fillet, Dijon mustard",
    roast_beef: "Roast Beef with Vegetable",
    roast_beef_desc: "Green beans, rib eye, olive oil, beef",
    marrkesh_text: "Marrkesh Vegetetarian Curruy",
    marrkesh_desc: "Sweet potato, eggplant, garbanzo beand",
    spicy_vegan: "Spicy Vegan Potato Curry",
    spicy_desc: "Coconut milk, beans, potatoes, curry powder",
    apple_text: "Apple Pie with Cream",
    apple_desc: "Whipping cream, egg white, cinnamon",
    lemon_text: "Lemon Meringue Pie",
    lemon_desc: "Frozen pie crust, meringue, lemon",
    author__desc: "They known for its fabulous taste and food. Anywhere you go your hunger is satisfied. The best chicken & burgers those are yummy.",
    placeholder_name: "Name",
    placeholder_email: "Email",
    placeholder_persons: "Persons",
    placeholder_timing: "Timing",
    placeholder_date: "Date",
    styleguide: "Styleguide",
    licenses: "Licenses",
    protected_page: "Protected",
    not_found: "Not Found"
  },
  ru: {
    nav_home: "Главная",
    nav_about: "О нас",
    author_desc_3: "Это место славится превосходным вкусом и великолепной кухней. Здесь вы всегда сможете утолить голод. Особенно вкусны жареная курица и бургеры.",
    nav_menu: "Наше меню",
    nav_pages: "Страницы",
    nav_blog: "Блог",
    nav_contact: "Контакты",
    call: "Звонок - 123 456 789",
    reservation_btn: "Бронирование",
    hero_title_1: "Добро пожаловать в",
    hero_title_2: "Ресторан",
    hero_desc: "Люди, еда и отличные места создают идеальную атмосферу для встреч с друзьями и семьей.",
    view_menu: "Посмотреть меню",
    locate_us: "Как нас найти",
    locate_address: "Riverside 25, Сан-Диего, Калифорния",
    open_hours: "Часы работы",
    open_time: "Пн-Пт 9:00 - 21:00",
    reservation: "Бронирование",
    story_title: "Вкусная история",
    story_desc: "Люди, еда и отличные места создают идеальную атмосферу для встреч с друзьями и семьей.",
    story_2018: "План открытия ресторана здорового питания.",
    story_2022: "Счастливый четвертый год работы.",
    menu_subtitle: "Меню",
    starters_title: "Попробуйте наши фирменные блюда",
    starters_text: "Каждый раз, когда вы идеально ужинаете с нами, это должно приносить радость от вдохновляющей еды в уникальной обстановке.",
    see_all_dishes: "Все блюда",
    starters: "Закуски",
    main_dish: "Основные блюда",
    desserts: "Десерты",
    testimonial_subtitle: "Отзывы",
    clients_say: "что говорят наши клиенты",
    clients_desc: "Мы любим слышать от клиентов, поэтому оставьте комментарий или напишите нам.",
    offers_subtitle: "предложения",
    offers_title: "Наши предложения",
    offers_desc: "Наши шеф-повара создают блюда, которые удовлетворят даже самого требовательного гурмана.",
    offer_going: "Скидка 50%",
    chicken_burger: "Куриный бургер",
    chicken_burger_desc: "Куриный бургер с вкусными добавками и листьями.",
    chicken_pizza: "Куриная пицца",
    chicken_pizza_desc: "Пицца с множеством вкусов и смешанными начинками.",
    only: "Только",
    author_desc_4: "Ресторан с уютным баром и комфортной обеденной зоной. Блюда здесь восхитительные, оригинальные и приготовлены с современным подходом. Обслуживание дружелюбное и профессиональное.",
    popular_subtitle: "меню",
    popular_title: "Популярные блюда",
    popular_desc: "В нашем ресторане официанты соревнуются в скорости обслуживания. Это привело к попытке побить рекорд Гиннесса.",
    chicken_manjoori: "Куриный Манджури",
    chicken_manjoori_desc: "Блюдо, любимое всеми возрастными группами как закуска на вечеринках.",
    hotdog: "Хот-дог",
    author_desc_2: "Я посещал этот замечательный ресторан несколько раз. Еда здесь просто превосходная, а качество обслуживания и внимание к каждой детали находятся на высочайшем уровне.",
    hotdog_desc: "Жареная сосиска в разрезанной булочке.",
    fresh_salmon: "Свежий лосось",
    fresh_salmon_desc: "Укрепите здоровье с нашим супер полезным соком.",
    veg_burger: "Овощной бургер",
    veg_burger_desc: "Бургеры могут быть приготовлены из таких ингредиентов, как бобы.",
    what_we_offer: "Что мы предлагаем",
    our_services: "Наши услуги",
    services_desc: "Атмосфера создает настроение. Это больше, чем просто обеденная зона. Еда выходит на первый план.",
    opened_247: "Работаем 24/7",
    special_menus: "Специальные меню",
    home_delivery: "Доставка на дом",
    blog_subtitle: "Блог",
    blog_title: "Будьте первым, кто узнает новости",
    blog_desc: "Читайте последние истории о наших блюдах, предложениях, мероприятиях и планах.",
    view_more: "Подробнее",
    blog_cat_delicious: "Вкусно",
    blog_cat_cooking: "Кулинария",
    blog_story_1: "Легенда американской кухни: История голодных людей",
    blog_story_1_desc: "Используйте простые стратегии для создания ценности и тестирования качества еды.",
    blog_story_2: "Самая популярная еда средиземноморской кухни",
    blog_story_2_desc: "Стратегии для создания ценности и тестирования качества еды.",
    reserve_subtitle: "бронирование",
    book_table: "Забронируйте столик",
    contact: "Контакты",
    working_hours: "Часы работы",
    subscribe_content: "Присоединяйтесь к нашему списку рассылки для обновлений.",
    submit: "Отправить",
    mon_fri: "Пн - Пт:",
    sat: "Сб:",
    sun: "Вс:",
    copyright: `© Авторские права - TastEat | Разработано <a href="https://www.victorflow.com/" target="_blank">VictorFlow</a> - На платформе <a href="https://webflow.com/" target="_blank">Webflow</a>`,
    raw_scallops: "Сырые гребешки из Эрки",
    raw_scallops_desc: "Откройте гребешок как устрицы",
    spring_roll: "Спринг-ролл",
    spring_roll_desc: "Добавьте масло в горячую сковороду с луком",
    french_onion: "Французский луковый суп",
    french_onion_desc: "Пшеничная мука, яблочный уксус, хлеб",
    tomato_bruschetta: "Томатная брускетта",
    tomato_bruschetta_desc: "Хлеб, оливковое масло, чеснок, черный перец",
    grilled_salmon: "Жареный лосось с укропным соусом",
    grilled_salmon_desc: "Коричневый сахар, филе лосося, горчица Дижон",
    roast_beef: "Жареная говядина с овощами",
    roast_beef_desc: "Зеленая фасоль, рибай, оливковое масло, говядина",
    marrkesh_text: "Марракешское вегетарианское карри",
    marrkesh_desc: "Батат, баклажан, нут",
    spicy_vegan: "Острое веганское карри с картофелем",
    spicy_desc: "Кокосовое молоко, фасоль, картофель, порошок карри",
    apple_text: "Яблочный пирог со сливками",
    apple_desc: "Взбитые сливки, яичный белок, корица",
    lemon_text: "Лимонный пирог с меренгой",
    lemon_desc: "Замороженное тесто, меренга, лимон",
    author__desc: "Они известны своим потрясающим вкусом и едой. Где бы вы ни были, ваш голод будет удовлетворен.",
    placeholder_name: "Имя",
    placeholder_email: "Электронная почта",
    placeholder_persons: "Количество гостей",
    placeholder_timing: "Время",
    placeholder_date: "Дата",
    styleguide: "Стили",
    licenses: "Лицензии",
    protected_page: "Защищено",
    not_found: "Не найдено"
  },

  uz: {
     nav_home: "Bosh sahifa",
    nav_about: "Biz haqimizda",
    author_desc_3: "O'zining ajoyib ta'mi va mazali taomlari bilan mashhur. Bu yerda ochligingiz albatta qondiriladi. Ayniqsa, qovurilgan tovuq va burgerlari juda mazali.",
    nav_menu: "Menyumiz",
    nav_pages: "Sahifalar",
    nav_blog: "Blog",
    nav_contact: "Biz bilan bog'lanish",
    call: "Qo'ng'iroq - 123 456 789",
    reservation_btn: "Bron qilish",
    hero_title_1: "Restoranga",
    hero_title_2: "Xush kelibsiz",
    hero_desc: "Odamlar, ovqat va joylar do'stlar va oila birga yig'iladigan mukammal muhit yaratadi.",
    view_menu: "Menyuni ko'rish",
    locate_us: "Manzilimiz",
    locate_address: "Riverside 25, San Diego, Kaliforniya",
    open_hours: "Ish vaqti",
    open_time: "Dush-Juma 9:00 - 21:00",
    reservation: "Bron qilish",
    story_title: "Mazali hikoya",
    story_desc: "Odamlar, ovqat va joylar do'stlar va oila birga yig'iladigan mukammal muhit yaratadi.",
    story_2018: "Sog'lom ovqat beradigan restoran ochish rejalari.",
    story_2022: "To'rtinchi yilni muvaffaqiyatli yakunladik.",
    menu_subtitle: "Menyu",
    author_desc_4: "Shinam bar va qulay ovqatlanish zaliga ega ajoyib restoran. Taomlari nihoyatda mazali, o'ziga xos va zamonaviy usulda tayyorlanadi. Xizmat ko'rsatish esa samimiy va professional darajada.",
    starters_title: "Bizning maxsus taomlarimizni sinab ko'ring",
    starters_text: "Har safar biz bilan mukammal ovqatlaningizda, noyob muhitda ilhomlangan ovqatdan zavq olishingiz kerak.",
    see_all_dishes: "Barcha taomlarni ko'rish",
    starters: "Starterlar",
    main_dish: "Asosiy taom",
    desserts: "Shirinliklar",
    testimonial_subtitle: "Sharhlar",
    clients_say: "mijozlarimiz nima deydi",
    clients_desc: "Mijozlardan eshitishni yaxshi ko'ramiz, izoh qoldiring yoki xabar yozing.",
    offers_subtitle: "takliflar",
    offers_title: "Bizning takliflarimiz",
    offers_desc: "Oshpazlarimiz hatto eng talabchan mijozlarni ham qondiradigan taomlar yaratadi.",
    offer_going: "50% Chegirma",
    chicken_burger: "Tovuq burger",
    chicken_burger_desc: "Mazali qo'shimchalar va barglar bilan tovuq burger.",
    chicken_pizza: "Tovuq pizza",
    chicken_pizza_desc: "Ko'p lazzatli va aralashtirilgan qo'shimchali pizza.",
    only: "Faqat",

    author_desc_2: "Men bu ajoyib restoranga bir necha bor tashrif buyurganman. Taomlari nihoyatda mazali, xizmat sifati esa har bir mayda tafsilotigacha mukammal darajada yo'lga qo'yilgan.",
    popular_subtitle: "menyu",
    popular_title: "Mashhur taomlar",
    popular_desc: "Restoranimizda ofitsiantlar eng tez xizmat ko'rsatish uchun raqobatlashadi. Bu Ginnes rekordini buzishga olib keldi.",
    chicken_manjoori: "Tovuq Manjuri",
    chicken_manjoori_desc: "Barcha yoshdagi odamlar ziyofatlarda boshlang'ich taom sifatida yoqtiradigan taom.",
    hotdog: "Xot-dog",
    hotdog_desc: "Yarim kesilgan non ichiga qo'yilgan qovurilgan kolbasa.",
    fresh_salmon: "Yangi losos",
    fresh_salmon_desc: "Sog'ligimizni Super Immune Juice bilan mustahkamlang.",
    veg_burger: "Sabzavotli burger",
    veg_burger_desc: "Burgerni loviya kabi ingredientlardan tayyorlash mumkin.",
    what_we_offer: "Nima taklif qilamiz",
    our_services: "Bizning xizmatlarimiz",
    services_desc: "Atmosfera sahna o'rnatadi. Bu shunchaki ovqat xonasi emas. Ovqat mehmonlar oldida.",
    opened_247: "24/7 ochiq",
    special_menus: "Maxsus menyu",
    home_delivery: "Yetkazib berish",
    blog_subtitle: "Blog",
    blog_title: "Birinchi bo'lib yangiliklarni o'qing",
    blog_desc: "Taomlarimiz, takliflarimiz, tadbirlarimiz va rejalariimiz haqida so'nggi hikoyalarni o'qing.",
    view_more: "Ko'proq ko'rish",
    blog_cat_delicious: "Mazali",
    blog_cat_cooking: "Pazandalik",
    blog_story_1: "AQSh oshxonasi afsonasi: Charchagan odamlar hikoyasi",
    blog_story_1_desc: "Oddiy strategiyalar bilan qiymat yaratish va ovqat sifatini sinash.",
    blog_story_2: "O'rta er dengizi oshxonasining eng mashhur taomi",
    blog_story_2_desc: "Qiymat yaratish va ovqat sifatini sinash uchun strategiyalar.",
    reserve_subtitle: "bron qilish",
    book_table: "Stolni bron qiling",
    contact: "Aloqa",
    working_hours: "Ish vaqti",
    subscribe_content: "Yangiliklar uchun pochta ro'yxatimizga qo'shiling.",
    submit: "Yuborish",
    mon_fri: "Dush-Juma:",
    sat: "Shanba:",
    sun: "Yakshanba:",
    
    copyright: `© Muallif huquqi - TastEat | Dizayn <a href="https://www.victorflow.com/" target="_blank">VictorFlow</a> - Texnologiya <a href="https://webflow.com/" target="_blank">Webflow</a>`,
    raw_scallops: "Erquy dan xom qisqichbaqa",
    raw_scallops_desc: "Qisqichbaqani ustrixon uchun oching",
    spring_roll: "Sprinq roll",
    spring_roll_desc: "Issiq tovaga piyoz oqlarini qo'shib moy qo'shing",
    french_onion: "Fransuz piyoz sho'rvasi",
    french_onion_desc: "Bug'doy uni, olma sirkasi, non",
    tomato_bruschetta: "Pomidor brushetta",
    tomato_bruschetta_desc: "Non, zaytun moyi, sarimsoq, qora qalampir",
    grilled_salmon: "Dill sous bilan qovurilgan losos",
    grilled_salmon_desc: "Qora shakar, losos file, Dijon gorchitsasi",
    roast_beef: "Sabzavot bilan qovurilgan mol go'shti",
    roast_beef_desc: "Yashil loviya, go'sht bo'lagi, zaytun moyi",
    marrkesh_text: "Marrkesh sabzavotli kari",
    marrkesh_desc: "Shirin kartoshka, bademjon, nisholda",
    spicy_vegan: "Achchiq vegan kartoshka kari",
    spicy_desc: "Kokos sut, loviya, kartoshka, kari kukuni",
    apple_text: "Qaymoq bilan olma pirogi",
    apple_desc: "Ko'pirtirilgan qaymoq, tuxum oqi, dolchin",
    lemon_text: "Limon meringue pirogi",
    lemon_desc: "Muzlatilgan xamir, meringue, limon",
    author__desc: "Ular ajoyib ta'mi va ovqati bilan tanilgan. Qayerda bo'lsangiz ham, ochligingiz qondiriladi.",
    placeholder_name: "Ism",
    placeholder_email: "Elektron pochta",
    placeholder_persons: "Mehmonlar soni",
    placeholder_timing: "Vaqt",
    placeholder_date: "Sana",
    styleguide: "Uslublar",
    licenses: "Litsenziyalar",
    protected_page: "Himoyalangan",
    not_found: "Topilmadi"
  }
}


